<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMquIVJf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMquIVJf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMquIVJf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMquIVJf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMquIVJf\App_KernelDevDebugContainer([
    'container.build_hash' => 'MquIVJf',
    'container.build_id' => '3f1e82f2',
    'container.build_time' => 1674033769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMquIVJf');
