<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoIny5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoIny5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoIny5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoIny5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoIny5x\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoIny5x',
    'container.build_id' => 'cfe197d3',
    'container.build_time' => 1673869849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoIny5x');
