<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2IJZdN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2IJZdN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2IJZdN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ2IJZdN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ2IJZdN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q2IJZdN',
    'container.build_id' => '81f53e9e',
    'container.build_time' => 1673610004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2IJZdN');
